[package]
name = "flouze-jni"
version = "0.1.0"
authors = ["Adrien Bustany <adrien@bustany.org>"]

[lib]
path = "src/main/rust/lib.rs"
crate_type = ["cdylib"]

[dependencies]
jni = "^0.12"
prost = "^0.5"
flouze = { path = "../lib" }
