---
# Travis does not support multi language files, so we'll have to do it
# ourselves...
# See https://github.com/travis-ci/travis-ci/issues/4090
language: minimal

# Looks like we need this to get SHM support (needed by Sled)
sudo: required

before_install:
  - "./travis/setup_rust.sh"
  - "./travis/setup_android_sdk.sh"
  - "./travis/setup_flouze_flutter_toolchains.sh"

script: |
  export PATH=$HOME/.cargo/bin:$PATH
  (cd lib && cargo build && cargo test) &&
  (cd flouze_flutter && RUST_RELEASE=nightly-2018-07-18 ./build-jni-libs.sh)

cache:
  timeout: 1000
  directories:
    - "$HOME/.cargo"
    - "$HOME/.local/android-sdk-linux"
    - "$HOME/.local/android-ndk-r18"
    - "$TRAVIS_BUILD_DIR/target"
    - "$HOME/.local/ndk-toolchains"
