version: 2
jobs:
  build:
    docker:
      - image: abustany/flouze-build@sha256:68d0de20a95d5974d8b3e9599bfebf1c12835f3183194f126ff66c69b435c368
    steps:
      - restore_cache:
          keys:
            - "v1-cargo"
            - "v1-git"
            - "v1-flutter-cache"
            - "v1-rust"
      - checkout
      - run:
          name: Setup environment variables
          command: |-
            echo RELEASE_NAME="${CIRCLE_BRANCH}-$(echo -n ${CIRCLE_SHA1} | tail -c10)" >> $BASH_ENV
      - run:
          name: Create the artifacts directory
          command: mkdir -p artifacts
      - run:
          name: Run Rust tests
          command: cargo build && cargo test
      - run:
          name: Build flouze-cli in release mode
          command: |-
            set -e
            cargo build --release -p flouze-cli
            cp target/release/flouze-cli artifacts/flouze-cli-${RELEASE_NAME}-linux-x86_64
      - run:
          name: Build JNI libs for the app
          command: cd flouze_flutter && RUST_RELEASE="nightly-$RUSTC_RELEASE_DATE" ./build-jni-libs.sh --release
      - run:
          name: Build the app
          command: |-
            set -e
            cd mobile
            flutter packages get
            flutter packages pub run build_runner build
            flutter build apk
            cp build/app/outputs/apk/release/app-release.apk ../artifacts/flouze-${RELEASE_NAME}.apk
      - store_artifacts:
          path: "artifacts"
      # Clean our own artifacts so that they don't clutter the cache
      - run:
          name: Clean Rust build directory before caching it
          command: cargo clean -p flouze && cargo clean -p flouze-cli && cargo clean -p flouze-jni && cargo clean -p flouze-flutter
      - save_cache:
          key: "v1-rust"
          paths:
            - "target"
      - save_cache:
          key: "v1-flutter-cache"
          paths:
            - "/home/ci/.local/flutter/.pub-cache"
      - save_cache:
          key: "v1-git"
          paths:
            - ".git"
      - save_cache:
          key: "v1-cargo"
          paths:
            - "/home/ci/.cargo"
