[package]
name = "flouze-cli"
version = "0.1.0"
authors = ["Adrien Bustany <adrien@bustany.org>"]

[dependencies]
error-chain = "^0.12.0"
rand = "^0.5.0"
structopt = "^0.2"
structopt-derive = "^0.2"

flouze = { path = "../lib" }
