[package]
name = "flouze-flutter"
version = "0.1.0"
authors = ["Adrien Bustany <adrien@bustany.org>"]

[lib]
path = "rust/lib.rs"
crate_type = ["staticlib", "cdylib"]

[dependencies]
bytes = "^0.4"
jni = "^0.12"
prost = "^0.5"
flouze = { path = "../lib" }

[build-dependencies]
prost-build = "^0.5"
