name: flouze_flutter
description: Flouze bindings for Flutter
version: 0.0.1
author: Adrien Bustany
homepage:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  protobuf: "^1.0.0"

dev_dependencies:
  protoc_plugin: "^19.0.1"
  test: "1.6.3"
  uuid: "^2.0.1"
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: org.bustany.flouze.flouzeflutter
    pluginClass: FlouzeFlutterPlugin
